spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://www.rychz.com:3306/data_convertor?characterEncoding=utf8
      username: bock
      password: c2012_LOGIN